# Connect Frontend to Colab Backend
# This script helps you quickly configure the frontend to use your Colab backend

Write-Host ""
Write-Host "🚀 Frontend-Backend Connection Setup" -ForegroundColor Cyan
Write-Host "=====================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env.local already exists
if (Test-Path ".env.local") {
    Write-Host "⚠️  .env.local file already exists!" -ForegroundColor Yellow
    Write-Host ""
    $overwrite = Read-Host "Do you want to update it? (y/n)"
    if ($overwrite -ne 'y') {
        Write-Host "❌ Cancelled. Existing .env.local file kept." -ForegroundColor Red
        exit
    }
}

Write-Host ""
Write-Host "📋 Instructions:" -ForegroundColor Green
Write-Host "   1. Make sure your Colab notebook is running (Step 4)"
Write-Host "   2. Look for the output that says:" -ForegroundColor Gray
Write-Host "      📡 Public URL: https://abc123.ngrok.io" -ForegroundColor Gray
Write-Host "   3. Copy that URL (e.g., https://abc123.ngrok.io)" -ForegroundColor Gray
Write-Host ""

# Get ngrok URL from user
$ngrokUrl = Read-Host "📡 Paste your ngrok URL here (or press Enter for localhost)"

# Validate input
if ([string]::IsNullOrWhiteSpace($ngrokUrl)) {
    $ngrokUrl = "http://localhost:8000"
    Write-Host "✅ Using local backend: $ngrokUrl" -ForegroundColor Yellow
} else {
    # Clean up URL (remove trailing slash, /api, etc.)
    $ngrokUrl = $ngrokUrl.Trim()
    $ngrokUrl = $ngrokUrl.TrimEnd('/')
    $ngrokUrl = $ngrokUrl -replace '/api$', ''
    
    # Validate URL format
    if ($ngrokUrl -notmatch '^https?://') {
        Write-Host "❌ Invalid URL format. Must start with http:// or https://" -ForegroundColor Red
        exit
    }
    
    Write-Host "✅ Using Colab backend: $ngrokUrl" -ForegroundColor Green
}

# Create .env.local file
$envContent = @"
# Frontend Environment Configuration
# Auto-generated by connect-to-colab.ps1

# Backend API URL
NEXT_PUBLIC_API_URL=$ngrokUrl

# Notes:
# - This URL is used by the frontend to connect to the backend
# - For Colab: Copy the ngrok URL from Step 4 output
# - For Local: Use http://localhost:8000
# - Do NOT include /api at the end
# - Restart frontend after changing this file (npm start)
"@

$envContent | Out-File -FilePath ".env.local" -Encoding utf8
Write-Host ""
Write-Host "✅ .env.local file created!" -ForegroundColor Green
Write-Host ""

# Show next steps
Write-Host "📋 Next Steps:" -ForegroundColor Cyan
Write-Host ""
Write-Host "   1. Restart the frontend:" -ForegroundColor White
Write-Host "      - Press Ctrl+C in the terminal running 'npm start'" -ForegroundColor Gray
Write-Host "      - Then run: npm start" -ForegroundColor Gray
Write-Host ""
Write-Host "   2. Open http://localhost:3000" -ForegroundColor White
Write-Host ""
Write-Host "   3. Look for the green 'Backend Connected' badge at the top" -ForegroundColor White
Write-Host ""
Write-Host "   4. Try translating a query!" -ForegroundColor White
Write-Host ""

# Offer to restart frontend
$restart = Read-Host "Would you like me to restart the frontend now? (y/n)"
if ($restart -eq 'y') {
    Write-Host ""
    Write-Host "🔄 Restarting frontend..." -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Note: This will start in this terminal." -ForegroundColor Yellow
    Write-Host "Press Ctrl+C to stop the server." -ForegroundColor Yellow
    Write-Host ""
    Start-Sleep -Seconds 2
    npm start
} else {
    Write-Host ""
    Write-Host "✅ Configuration complete!" -ForegroundColor Green
    Write-Host "   Run 'npm start' when you're ready." -ForegroundColor Gray
    Write-Host ""
}
